### ISSUE TITLE
Setup: Create a README.md file for your `bootcamp-schedule` repository

### ISSUE THREAD

**Issue by codingbootcampseu** [Zoneyem/bootcamp-schedule#4]
You will use your `bootcamp-schedule` repository on a daily basis during the bootcamp.

Add a new file called `README.md` and add some content:

- [ ] Heading and text that states that this is your personal repo to track your progress within our bootcamp
- [ ] Add a TIL (today I learned) section with all the things you learned so far
- [ ] Update the TIL list every day

**Comment by Zoneyem** [comment]
Today i met new awesome pleople. I also learned about Github and to deal with it. There was also an intro du Git
